#!/bin/bash
set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD:-change_me_root}" <<EOF
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE:-buypeer};
CREATE USER IF NOT EXISTS '${MYSQL_USER:-buypeer}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD:-change_me}';
CREATE USER IF NOT EXISTS '${MYSQL_USER:-buypeer}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD:-change_me}';
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER:-buypeer}'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER:-buypeer}'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF

exec "$@"